doctrine mappings: annotations --> attrributes
dotkernel/api pull request #210
Opened 2023-10-31 15:23 UTC by cPintiuta

changed all entities that uses doctrine annotation mappings with doctrine attribute mappings
#209

2023-10-31 16:54 UTC, alexmerlin requested changes

2023-10-31 16:54 UTC, alexmerlin commented on src/User/src/Entity/User.php
> +    #[ORM\Column("status", type: "string", length: 20)]
```suggestion
    #[ORM\Column(name: "status", type: "string", length: 20)]
```

2023-10-31 16:54 UTC, alexmerlin commented on src/User/src/Entity/User.php
> +    #[ORM\Column("isDeleted", type: "boolean")]
```suggestion
    #[ORM\Column(name: "isDeleted", type: "boolean")]
```

2023-10-31 16:54 UTC, alexmerlin commented on src/User/src/Entity/UserResetPasswordEntity.php
> +#[ORM\Entity, ORM\Table(name: "user_reset_password"), ORM\HasLifecycleCallbacks]
```suggestion
#[ORM\Entity]
#[ORM\Table(name: "user_reset_password")]
#[ORM\HasLifecycleCallbacks]
```
Just for better readability.

2023-10-31 16:54 UTC, alexmerlin commented on src/User/src/Entity/UserResetPasswordEntity.php
> +    #[ORM\ManyToOne(targetEntity: "User", cascade: ['persist', 'remove'], inversedBy: "resetPasswords")]
```suggestion
    #[ORM\ManyToOne(targetEntity: User::class, cascade: ['persist', 'remove'], inversedBy: "resetPasswords")]
```

2023-10-31 16:54 UTC, alexmerlin commented on src/User/src/Entity/UserRole.php
> +    public const ROLE_API_USER = 'api_user';
```suggestion
```

2023-10-31 16:54 UTC, alexmerlin commented on src/User/src/Entity/UserRole.php
> +        self::ROLE_API_USER,
```suggestion
```

2023-11-01 10:30 UTC, alexmerlin approved these changes

2023-11-01 13:11 UTC, MarioRadu approved these changes

2023-11-02 10:15 UTC, merged