Bump to PHP 8.3
dotkernel/api pull request #222
Opened 2024-02-26 15:28 UTC by bidi47

2024-02-26 15:41 UTC, alexmerlin requested changes

2024-02-26 15:41 UTC, alexmerlin commented on src/App/src/Factory/AnnotationsCacheFactory.php
Why should we remove this class/feature?
It caches all the annotations so they are not read/parsed/processed with each request.
Unless there is a reason that I'm not aware of...

2024-02-26 16:06 UTC, bidi47 commented on src/App/src/Factory/AnnotationsCacheFactory.php
the cache was removed (see local.php.dist) until an alternative was found
it will be added after the cache solution for the admin is checked

2024-02-26 16:11 UTC, alexmerlin commented on src/App/src/Factory/AnnotationsCacheFactory.php
Until then, please also remove the `annotations_cache_dir` key from `config/autoload/local.php.dist`.

2024-02-26 16:15 UTC, bidi47 commented on src/App/src/Factory/AnnotationsCacheFactory.php
removed annotations_cache_dir

2024-02-26 16:19 UTC, alexmerlin approved these changes

2024-02-27 10:06 UTC, arhimede approved these changes

2024-02-27 10:07 UTC, merged