Implemented API evolution pattern
dotkernel/api pull request #285
Opened 2024-06-14 08:36 UTC by MarioRadu

2024-06-14 13:47 UTC, alexmerlin requested changes

2024-06-14 13:47 UTC, alexmerlin commented on src/App/src/Message.php
> +    public const RESTRICTION_DEPRECATION          = 'Cannot use both `%s` and `%s` attributes on the same object.';
We try keep messages ordered alphabetically, so let's move this line up, after the one with `RESOURCE_NOT_ALLOWED`.
Also, I see that I misplaced `MAIL_NOT_SENT_TO` - let's move that too after `INVALID_VALUE`.

2024-06-14 13:47 UTC, alexmerlin commented on src/App/src/Middleware/DeprecationMiddleware.php
> +        $routeMiddleware   = $routeResult->getMatchedRoute()->getMiddleware();
```suggestion
        $routeMiddleware   = null;
        $matchedRoute      = $routeResult->getMatchedRoute();
        if ($matchedRoute !== false) {
            $routeMiddleware = $matchedRoute->getMiddleware();
        }
```

2024-06-14 13:47 UTC, alexmerlin commented on src/App/src/Middleware/DeprecationMiddleware.php
> +        } else {
```suggestion
        } elseif ($routeMiddleware !== null) {
```

2024-06-14 13:47 UTC, alexmerlin commented on src/App/src/Middleware/DeprecationMiddleware.php
> +        if ($attributes[self::RESOURCE_DEPRECATION_ATTRIBUTE] ?? '') {
```suggestion
        if (array_key_exists(self::RESOURCE_DEPRECATION_ATTRIBUTE, $attributes)) {
```

2024-06-14 13:47 UTC, alexmerlin commented on src/App/src/Middleware/DeprecationMiddleware.php
> +        if ($attributes[self::METHOD_DEPRECATION_ATTRIBUTE] ?? '') {
```suggestion
        if (array_key_exists(self::METHOD_DEPRECATION_ATTRIBUTE, $attributes)) {
```

2024-06-14 13:47 UTC, alexmerlin commented on src/App/src/Middleware/DeprecationMiddleware.php
> +        $sunset = '';
```suggestion
        $sunset = null;
```

2024-06-14 13:47 UTC, alexmerlin commented on src/App/src/Middleware/DeprecationMiddleware.php
> +        $link   = '';
```suggestion
        $link   = null;
```

2024-06-14 13:47 UTC, alexmerlin commented on src/App/src/Middleware/DeprecationMiddleware.php
> +        if ($sunset) {
```suggestion
        if ($sunset !== null) {
```

2024-06-14 13:47 UTC, alexmerlin commented on src/App/src/Middleware/DeprecationMiddleware.php
> +        if ($link) {
```suggestion
        if ($link !== null) {
```

2024-06-14 13:47 UTC, alexmerlin commented on src/App/src/Middleware/DeprecationMiddleware.php
> +    public function getAttributes(ReflectionClass|ReflectionMethod $reflection, string $type): array
```suggestion
    /**
     * @param class-string $type
     */
    public function getAttributes(ReflectionClass|ReflectionMethod $reflection, string $type): array
```

---

To fix this Psalm error:

> ArgumentTypeCoercion: Argument 1 of ReflectionClass::getAttributes expects class-string|null, but parent type string provided

2024-06-14 13:47 UTC, alexmerlin commented on src/App/src/Middleware/DeprecationMiddleware.php
> +            $reflectionMiddlewareClass = new ReflectionClass($routeMiddleware->middlewareName);
```suggestion
            /** @var class-string $routeMiddleware */
            $routeMiddleware           = $routeMiddleware->middlewareName;
            $reflectionMiddlewareClass = new ReflectionClass($routeMiddleware);
```

2024-06-14 13:47 UTC, alexmerlin commented on test/Unit/App/Attribute/MethodDeprecationTest.php
> +            public function test()
```suggestion
            public function test(): void
```

2024-06-14 13:47 UTC, alexmerlin commented on test/Unit/App/Attribute/MethodDeprecationTest.php
> +            public function test()
```suggestion
            public function test(): void
```

2024-06-14 13:47 UTC, alexmerlin commented on test/Unit/App/Middleware/DeprecationMiddlewareTest.php
> +    public function testThrowsDeprecationConflictException()
```suggestion
    public function testThrowsDeprecationConflictException(): void
```

2024-06-16 14:06 UTC, MarioRadu commented on src/App/src/Middleware/DeprecationMiddleware.php
> +        } else {
`$routeMiddleware` can't be null so I checked if it's an instance of `MiddlewarePipe `which implements `MiddlewareInterface`.

2024-06-17 04:26 UTC, alexmerlin approved these changes

2024-06-17 09:45 UTC, arhimede approved these changes

2024-06-17 09:45 UTC, merged