updated user status, removed isDeleted
dotkernel/api pull request #359
Opened 2024-12-02 18:07 UTC by bidi47

2024-12-03 13:22 UTC, alexmerlin requested changes

2024-12-03 13:22 UTC, alexmerlin commented on data/doctrine/migrations/Version20241030082958.php
> +        $this->addSql('CREATE TABLE user (uuid BINARY(16) NOT NULL, identity VARCHAR(191) NOT NULL, password VARCHAR(191) NOT NULL, status ENUM(\'active\', \'pending\') DEFAULT \'pending\' NOT NULL,
The new user status - `deleted` - is missing from the migration.
You must clear Doctrine cache before generating the migration, else Doctrine does not pick up the enum value changes.

2024-12-03 13:22 UTC, alexmerlin commented on src/App/src/Middleware/AuthorizationMiddleware.php
> +                if (! $user instanceof User || $user->getStatus() === UserStatusEnum::Deleted) {
```suggestion
                if (! $user instanceof User || $user->isDeleted()) {
```

2024-12-03 13:22 UTC, alexmerlin commented on src/User/src/Entity/User.php
> -    public function isDeleted(): bool
Let's keep this as a helper method, so we do't have to repeat comparing user->status against `UserStatusEnum::Deleted`. Move the metod after `isActive()` so we have all helper methods in one place.

2024-12-03 13:22 UTC, alexmerlin commented on src/User/src/Repository/UserRepository.php
>          }
```suggestion
        } else {
            $qb->andWhere('user.status != :status')->setParameter('status', UserStatusEnum::Deleted);
        }
```
This way, unless filtering by a specific status, we exclude deleted users.

2024-12-03 13:22 UTC, alexmerlin commented on test/Functional/AdminTest.php
> +        $this->assertTrue($user?->getStatus() === UserStatusEnum::Deleted);
```suggestion
        $this->assertTrue($user?->isDeleted());
```

2024-12-03 13:22 UTC, alexmerlin commented on test/Functional/UserTest.php
> +        $this->assertTrue($deletedUser?->getStatus() === UserStatusEnum::Deleted);
```suggestion
        $this->assertTrue($deletedUser?->isDeleted());
```

2024-12-03 13:24 UTC, alexmerlin commented
@bidi47 Also, let's create an Dotkernel API issue for this based on https://github.com/dotkernel/frontend/issues/523 then link that issue with this PR.

2024-12-03 15:26 UTC, bidi47 commented on data/doctrine/migrations/Version20241030082958.php
> +        $this->addSql('CREATE TABLE user (uuid BINARY(16) NOT NULL, identity VARCHAR(191) NOT NULL, password VARCHAR(191) NOT NULL, status ENUM(\'active\', \'pending\') DEFAULT \'pending\' NOT NULL,
updated in new commit

2024-12-04 06:35 UTC, alexmerlin commented
@arhimede 
When an (super)admin fetches a list of users, should the response contain deleted users as well?
Same question for when an admin tries to fetch a deleted user.

With the previous approach (using `isDeleted`):
* `list users` response **did** by default include `isDeleted=1` users as well (could be filtered, though)
* `view user by uuid` response did return `isDeleted=1` users as well (instead of throwing a `Not found` response)

2024-12-04 10:50 UTC, arhimede commented
> @arhimede When an (super)admin fetches a list of users, should the response contain deleted users as well? Same question for when an admin tries to fetch a deleted user.
> 
> With the previous approach (using `isDeleted`):
> 
>     * `list users` response **did** by default include `isDeleted=1` users as well (could be filtered, though)
> 
>     * `view user by uuid` response did return `isDeleted=1` users as well (instead of throwing a `Not found` response)

If a record is deleted in database, even Soft deleted, should not appear in any search results, in any endpoint

2024-12-04 15:18 UTC, alexmerlin requested changes

2024-12-04 15:18 UTC, alexmerlin commented on src/User/src/Service/UserService.php
> +        if (! $user instanceof User || $user->getStatus() === UserStatusEnum::Deleted) {
Is there any helper method that we could use to avoid comparing `$user->status` against `UserStatusEnum::Deleted`?

2024-12-04 15:18 UTC, alexmerlin commented on src/User/src/Service/UserService.php
`findByEmail()` should also make sure that the user is not deleted.

2024-12-05 10:55 UTC, bidi47 commented on src/User/src/Service/UserService.php
> +        if (! $user instanceof User || $user->getStatus() === UserStatusEnum::Deleted) {
i replaced with $user->isDeleted() in the new commit

2024-12-06 11:01 UTC, arhimede approved these changes

2024-12-06 11:01 UTC, alexmerlin approved these changes

2024-12-06 11:01 UTC, merged